/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.bonespirito.logtracing

import com.bonespirito.logtracing.configuration.LoggerProperties
import org.slf4j.LoggerFactory
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.boot.context.properties.EnableConfigurationProperties
import org.springframework.stereotype.Service

@Service
@EnableConfigurationProperties(LoggerProperties::class)
class LoggerTracing(
    @Autowired val properties: LoggerProperties
) {

    fun someLibraryMethod(): Boolean {
        val l = LoggerFactory.getLogger(LoggerTracing::class.java)
        l.info("properties: $properties")
        return true
    }
}
