/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.bonespirito.logtracing

import com.bonespirito.logtracing.configuration.LoggerProperties
import io.mockk.mockk
import org.junit.Test
import org.junit.jupiter.api.Assertions.assertTrue
import org.springframework.boot.test.context.SpringBootTest

@SpringBootTest("bonespirito.token=Hello")
open class LoggerTest {

    val properties: LoggerProperties = mockk()
    val classUnderTest: LoggerTracing = LoggerTracing(properties)

    @Test
    fun `test`() {
        assertTrue(classUnderTest.someLibraryMethod())
    }
}
